import assert from 'node:assert/strict';import{createServer}from'vite';import{chromium}from'playwright';
const server=await createServer({server:{host:'127.0.0.1',port:0}});await server.listen();let browser;
try{
 browser=await chromium.launch({executablePath:process.env.COMPAS_TEST_CHROMIUM,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/COMPAS_NG/`);
 const ges=()=>page.locator('.app-nav__tab').filter({hasText:'Gestor de Encuestas'}).click();
 await ges();
 const editor=page.locator('details.planning-instruments').first();
 await editor.locator(':scope > summary').click();
 await editor.getByLabel('Nombre de la propuesta',{exact:true}).fill('PRUEBA registro inicial');
 await editor.getByLabel('Población destinataria',{exact:true}).fill('Personas mayores participantes');
 await editor.getByLabel('Modalidad de recogida',{exact:true}).selectOption('Registro inicial');
 await editor.locator('.planning-instruments > summary').click();
 await editor.getByRole('button',{name:'Seleccionar para esta propuesta · Soledad — TIL (3 ítems)',exact:true}).click();
 await editor.getByRole('button',{name:'Guardar propuesta de recogida',exact:true}).click();
 await page.getByRole('button',{name:'Abrir propuesta · PRUEBA registro inicial',exact:true}).waitFor();
 await page.reload();await ges();await editor.locator(':scope > summary').click();
 await editor.getByRole('button',{name:'Abrir propuesta · PRUEBA registro inicial',exact:true}).click();
 assert.equal(await editor.getByLabel('Población destinataria',{exact:true}).inputValue(),'Personas mayores participantes');
 assert.equal(await editor.getByLabel('Modalidad de recogida',{exact:true}).inputValue(),'Registro inicial');
 assert.equal(await editor.getByRole('button',{name:'Retirar · Soledad — TIL (3 ítems)',exact:true}).count(),1);
 const downloading=page.waitForEvent('download');await editor.getByRole('button',{name:'Descargar especificación de trabajo'}).click();const download=await downloading;const stream=await download.createReadStream();const chunks=[];for await(const c of stream)chunks.push(c);const result=JSON.parse(Buffer.concat(chunks).toString());assert.deepEqual(result.configuration.ids,['til']);assert.match(result.purpose,/no es un cuestionario administrable/);

 await editor.getByRole('button',{name:'Duplicar propuesta',exact:true}).click();
 assert.equal(await editor.getByText('Cambios sin guardar',{exact:true}).count(),1);
 await editor.getByLabel('Nombre de la propuesta',{exact:true}).fill('PRUEBA seguimiento');
 await editor.getByLabel('Población destinataria',{exact:true}).fill('Participantes en seguimiento');
 page.once('dialog',dialog=>dialog.dismiss());
 await editor.getByRole('button',{name:'Abrir propuesta · PRUEBA registro inicial',exact:true}).click();
 assert.equal(await editor.getByLabel('Nombre de la propuesta',{exact:true}).inputValue(),'PRUEBA seguimiento');
 page.once('dialog',dialog=>dialog.dismiss());
 await page.locator('.app-nav__tab').filter({hasText:'Inicio'}).click();
 assert.equal(await editor.getByLabel('Nombre de la propuesta',{exact:true}).inputValue(),'PRUEBA seguimiento');
 await editor.getByRole('button',{name:'Guardar propuesta de recogida',exact:true}).click();
 await editor.getByRole('button',{name:'Abrir propuesta · PRUEBA seguimiento',exact:true}).waitFor();
 assert.equal(await editor.getByText('Sin cambios pendientes',{exact:true}).count(),1);
 await editor.getByRole('button',{name:'Abrir propuesta · PRUEBA registro inicial',exact:true}).click();
 assert.equal(await editor.getByLabel('Población destinataria',{exact:true}).inputValue(),'Personas mayores participantes');
 await editor.getByRole('button',{name:'Abrir propuesta · PRUEBA seguimiento',exact:true}).click();
 assert.equal(await editor.getByLabel('Población destinataria',{exact:true}).inputValue(),'Participantes en seguimiento');
 await editor.getByLabel('Justificación, adaptación pendiente y calendario',{exact:true}).fill('Edición pendiente');
 page.once('dialog',dialog=>dialog.dismiss());
 await editor.getByRole('button',{name:'Nueva propuesta',exact:true}).click();
 assert.equal(await editor.getByLabel('Justificación, adaptación pendiente y calendario',{exact:true}).inputValue(),'Edición pendiente');
 page.once('dialog',dialog=>dialog.accept());
 await editor.getByRole('button',{name:'Nueva propuesta',exact:true}).click();
 assert.equal(await editor.getByLabel('Nombre de la propuesta',{exact:true}).inputValue(),'');
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('PASS: composición modular, población, registro inicial, guardado y recuperación, descarga, duplicación independiente, protección de cambios y móvil');
}finally{await browser?.close();await server.close();}
