import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from 'playwright';
const server = await createServer({server:{host:'127.0.0.1',port:0}});
await server.listen();
let browser;
try {
  browser = await chromium.launch({headless:true, ...(process.env.COMPAS_TEST_CHROMIUM ? {executablePath:process.env.COMPAS_TEST_CHROMIUM} : {}), args:['--no-sandbox']});
  const page = await browser.newPage();
  const errors=[]; page.on('pageerror', error=>errors.push(error.message));
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/COMPAS_NG/?vista=coordinacion-zaidin`);
  assert.equal(await page.locator('input[type=password]').count(),0);
  await page.getByRole('button',{name:'Explorar como coordinación del Zaidín'}).click();
  const nav=page.getByRole('navigation',{name:'Áreas de coordinación'});
  assert.equal(await nav.getByRole('button').count(),5);
  for (const name of ['Fichas y aportaciones','Instrumentos y encuestas','Equipo y responsabilidades','Seguimiento del plan','Plan de Acción']) {
    await nav.getByRole('button',{name,exact:true}).click();
    assert.equal(await page.getByRole('heading',{name,exact:true}).count(),1);
  }
  const panel=page.locator('.pcm-preparation');
  assert.equal(await panel.locator('.pcm-general').count(),4);
  assert.equal(await panel.locator('select').count(),41);
  const autonomy=panel.locator('.pcm-general').filter({has:page.getByRole('heading',{name:'ENV-OE1.1',exact:true})});
  assert.equal(await autonomy.getByRole('heading',{name:'ENV-OE8.1',exact:true}).count(),0);
  await panel.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).selectOption('excluded');
  await panel.locator('.pcm-sheet').first().locator('summary').click();
  await panel.getByLabel('Selección de borrador ENV-I5.1',{exact:true}).selectOption('modified');
  await panel.getByLabel('Nueva redacción · ENV-I5.1',{exact:true}).fill('Indicador de prueba');
  await nav.getByRole('button',{name:'Equipo y responsabilidades',exact:true}).click();
  await nav.getByRole('button',{name:'Plan de Acción',exact:true}).click();
  assert.equal(await panel.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).inputValue(),'excluded');
  await panel.locator('.pcm-sheet').first().locator('summary').click();
  assert.equal(await panel.getByLabel('Nueva redacción · ENV-I5.1',{exact:true}).inputValue(),'Indicador de prueba');
  await panel.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).selectOption('included');
  if(process.env.COMPAS_TEST_SCREENSHOT) await page.screenshot({path:process.env.COMPAS_TEST_SCREENSHOT,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(await page.evaluate(()=>Object.keys(localStorage)),['compas-ng:demo:coordinacion-zaidin:v1']);
  await page.reload();
  await page.getByRole('button',{name:'Explorar como coordinación del Zaidín'}).click();
  assert.equal(await page.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).inputValue(),'included');
  await page.getByLabel('Recuperar borrador de prueba').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});
  await page.getByText('Archivo incompatible con este borrador de coordinación.',{exact:true}).waitFor();
  assert.equal(await page.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).inputValue(),'included');
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Descargar borrador de prueba'}).click();
  const download=await downloadPromise;
  const stream=await download.createReadStream(); const chunks=[];
  for await (const chunk of stream) chunks.push(chunk);
  const exported=Buffer.concat(chunks);
  await page.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).selectOption('excluded');
  await page.getByLabel('Recuperar borrador de prueba').setInputFiles({name:'draft.json',mimeType:'application/json',buffer:exported});
  await page.getByRole('button',{name:'Sustituir borrador de prueba'}).click();
  assert.equal(await page.getByLabel('Selección de borrador ENV-OE5.1',{exact:true}).inputValue(),'included');
  await page.getByRole('button',{name:'Salir del ejemplo'}).click();
  assert.equal(await page.getByRole('heading',{name:'Tu espacio de coordinación del Zaidín'}).count(),1);
  assert.deepEqual(errors,[]);
  console.log('PASS: 41 controles, edición de indicador, exclusión y recuperación, cambio de área, accesibilidad reagrupada; entrada, cinco áreas, salida, sin escrituras municipales, sin contraseña ficticia, móvil y sin errores JS');
} finally {await browser?.close();await server.close();}
