export type {
  PlanningPeriod,
  InstitutionalApproval,
  UnaddressedNeed,
  PLSSectionResumenEjecutivo,
  PLSSectionPortada,
  PLSSectionMarcoInstitucional,
  PLSSectionContextoTerritorial,
  PLSSectionDiagnosticoTerritorial,
  PLSSectionPriorizacion,
  PLSSectionArticulacionInstitucional,
  PLSSectionPlanAccion,
  PLSSectionAgenda,
  PLSSectionSeguimiento,
  PLSSectionGobernanza,
  PLSSectionAnexosMetodologicos,
  LocalHealthPlanDocument,
} from "./LocalHealthPlanDocument";
