export type {
  EKCSnapshot,
  PSLCArtifactHipotesis,
  PSLCArtifactPreguntaAbierta,
  PSLCArtifactPortada,
  PSLCArtifactIdentificacion,
  PSLCArtifactMarcoEstrategico,
  PSLCArtifactInformeSalud,
  PSLCArtifactBaseDocumental,
  PSLCArtifactAreaIntervencion,
  PSLCArtifactLecturaTerritorial,
  PSLCArtifactConclusiones,
  PSLCArtifactCierreInterpretativo,
  PSLCArtifactCandidatura,
  PSLCArtifactPriorizacion,
  PSLCArtifactNotaValidacion,
  PSLCArtifactCautelas,
  LocalHealthProfileArtifact,
} from "./LocalHealthProfileArtifact";
