/** Catálogo de preparación. No contiene respuestas, puntuaciones ni cuestionarios ejecutables. */
export interface PlanningInstrument {
 id: string; name: string; axis: string; objectives: string[]; population: string;
 evidence: string; limitation: string; reference?: string;
 kind: 'Escala candidata' | 'Registro o preguntas por desarrollar';
}
const scale = (id:string,name:string,axis:string,objectives:string[],population:string,evidence:string,limitation:string,reference:string):PlanningInstrument => ({id,name,axis,objectives,population,evidence,limitation,reference,kind:'Escala candidata'});
const record = (id:string,name:string,axis:string,objectives:string[],population:string,limitation:string):PlanningInstrument => ({id,name,axis,objectives,population,evidence:'Propuesta propia pendiente de diseño y pilotaje.',limitation,kind:'Registro o preguntas por desarrollar'});
export const PLANNING_INSTRUMENTS: PlanningInstrument[] = [
 scale('cenve','CENVE','Edadismo',['ENV-OE5.1'],'Jóvenes y adultos','Estudio psicométrico español en jóvenes y adultos.','Concretar edades escolares; no asumir validación para cualquier etapa educativa.','https://pubmed.ncbi.nlm.nih.gov/26826942/'),
 scale('aaoas','Actitudes edadistas en adolescentes — AAOAS','Edadismo',['ENV-OE5.1'],'Adolescentes','Desarrollo y validación inicial publicados.','Versión española adecuada pendiente de confirmar; el estudio señala aspectos que requieren revisión.','https://pubmed.ncbi.nlm.nih.gov/33592099/'),
 scale('who-ageism','Experiencias de edadismo — OMS','Edadismo',['ENV-OE5.2'],'Personas mayores','La campaña de la OMS ofrece versión española de experiencias de edadismo.','Experiencias de trato no equivalen a visibilidad ni reconocimiento: cobertura parcial del objetivo.','https://www.aworld4allages.org/who-ageism-scale'),
 scale('til','Soledad — TIL (3 ítems)','Soledad no deseada',['ENV-OE2.1','ENV-OE2.2'],'Personas mayores','Validación española con participación de personas mayores.','No mide por sí sola red social; definir finalidad y criterios antes de detección.','https://doi.org/10.1080/02109395.2021.1989889'),
 scale('djg','Soledad — De Jong Gierveld (11 ítems)','Soledad no deseada',['ENV-OE2.1','ENV-OE2.2'],'Personas mayores','Estudio factorial en personas mayores españolas.','Alternativa a TIL; no trasladar la evidencia automáticamente a versiones abreviadas.','https://scielo.isciii.es/scielo.php?pid=S0212-97282014000200022&script=sci_arttext'),
 scale('lsns6','Red social — Lubben LSNS-6','Soledad no deseada',['ENV-OE3.1'],'Personas mayores','Validación en español realizada en Argentina.','No equivale a validación en España ni a medición de soledad percibida.','https://pubmed.ncbi.nlm.nih.gov/33351375/'),
 scale('duke11','Apoyo social — Duke-UNC-11','Soledad no deseada',['ENV-OE3.2'],'Personas adultas y mayores','Validación española del apoyo social funcional.','Revisar versión y uso; no confundir con variables derivadas DUKE-EAS.','https://pubmed.ncbi.nlm.nih.gov/8962994/'),
 scale('casp12','Calidad de vida y autonomía — CASP-12','Autonomía',['ENV-OE1.1'],'Personas mayores','Validación española en personas de 60 o más años.','Cobertura parcial de autonomía amplia. No crear subescalas ni recortar ítems sin justificación.','https://pubmed.ncbi.nlm.nih.gov/28282724/'),
 scale('whoqolold','Calidad de vida — WHOQOL-OLD','Autonomía',['ENV-OE1.1','ENV-OE4.1'],'Personas mayores','Estudio de adecuación en personas mayores españolas.','Revisar administración conjunta, dimensiones y carga de respuesta.','https://pubmed.ncbi.nlm.nih.gov/21815852/'),
 scale('who5','Bienestar — OMS-5','Autonomía',['ENV-OE1.2'],'Personas adultas y mayores','Versión oficial española de cinco ítems.','Reconocimiento oficial no implica validación específica en el Zaidín.','https://www.who.int/es/publications/m/item/WHO-UCN-MSD-MHE-2024.01'),
 scale('digcomp','Competencias digitales — DigCompB_PM','Participación',['ENV-OE9.1','ENV-OE9.2'],'Personas mayores','Estudio en 210 personas de 65 o más años de Valencia y su entorno.','Autoinforme de competencias; no cubre por sí solo acceso a dispositivos o realización efectiva de trámites.','https://www.e-iji.net/dosyalar/iji_2025_1_5.pdf'),
 scale('afccq','Comunidades amigables — AFCCQ','Participación',['ENV-OE4.1','ENV-OE8.1','ENV-OE8.2'],'Personas mayores','Desarrollo y validación originales publicados.','Versión española validada no confirmada en esta revisión.','https://www.mdpi.com/1660-4601/17/18/6867'),
 record('recognition','Visibilidad y reconocimiento comunitario','Edadismo',['ENV-OE5.2'],'Población general y personas mayores','Separar alcance de campañas, diversidad de representación y reconocimiento percibido.'),
 record('detection','Detección, valoración y respuesta','Soledad no deseada',['ENV-OE2.1','ENV-OE7.2'],'Agentes comunitarios','Registrar fechas y continuidad; no interpretar un aumento de detecciones como aumento de prevalencia.'),
 record('agents','Capacidad de agentes y contribución de activos','Soledad no deseada',['ENV-OE6.1','ENV-OE6.2'],'Agentes y responsables de entidades','Distinguir competencia declarada, prácticas observadas y actuaciones realizadas.'),
 record('agency','Decisión, relaciones y apoyos para la autonomía','Autonomía',['ENV-OE1.1'],'Personas mayores','Preguntas diferenciadas por dimensión; necesitar apoyos no implica carecer de autonomía.'),
 record('participation','Participación significativa e influencia','Participación',['ENV-OE4.1','ENV-OE4.2'],'Personas mayores','Distinguir asistencia, significado personal y capacidad de influir en decisiones.'),
 record('barriers','Barreras y acceso efectivo a recursos','Participación',['ENV-OE8.1','ENV-OE8.2'],'Personas mayores y responsables de recursos','Separar barreras físicas, económicas, informativas, organizativas y de comunicación; contrastar experiencia y actuaciones.'),
 record('digital-access','Acceso digital y gestiones esenciales','Participación',['ENV-OE9.1','ENV-OE9.2'],'Personas mayores','Diferenciar disponibilidad, dificultad declarada, apoyos y ejecución de gestiones.'),
 record('coordination','Participación y acuerdos de coordinación','Participación',['ENV-OE7.1'],'Responsables de entidades','Registrar continuidad y cumplimiento de acuerdos, además de asistencia a reuniones.'),
];
export const COLLECTION_USES = ['Encuesta temática o combinada','Registro inicial','Seguimiento de una actuación','Evaluación final o posterior'] as const;
